"""Generate `docs/METHODS.md`, `docs/HYPERPARAMETERS.md` and `docs/METRICS.md`.

These three files are derived from the registries, never hand-edited, and
`tests/unit/test_docs_in_sync.py` fails when the committed copy differs from what the
registries currently say. That check exists because of a specific failure in the code this
was ported from: its documentation claimed 39 methods in one file, 31 in another, 12
filter strategies in a third and 14 in a fourth, and every number was wrong somewhere.

`METRICS.md` goes one step further than reading the registry: it *runs* each group on a
small synthetic fixture and lists the keys that actually come back. A hand-written key list
is a promise; this is an observation, and it cannot drift from the code that produces it.

Regenerate with:

    python3.11 scripts/generate_docs.py
"""

from __future__ import annotations

import warnings
from typing import Any, Callable

BANNER = (
    "<!-- Generated by scripts/generate_docs.py from the registries. Do not edit by "
    "hand: tests/unit/test_docs_in_sync.py will fail. -->"
)

# Group F shells out to Rscript, so its keys cannot be probed where R is absent. Listing
# it as un-probed unconditionally keeps this file byte-identical in every environment -
# otherwise the docs would differ between a laptop and the image, and the sync test would
# fail depending on where it ran.
UNPROBED_GROUPS = frozenset("F")


def _fixture():
    """A tiny, deterministic dataset for probing which keys each group emits."""
    import numpy as np
    import pandas as pd

    rng = np.random.default_rng(0)
    n_samples, n_genes = 40, 50
    samples = [f"S{i:03d}" for i in range(n_samples)]
    exp_df = pd.DataFrame(
        rng.lognormal(3.0, 1.0, size=(n_samples, n_genes)),
        index=samples,
        columns=[f"GENE{j:03d}" for j in range(n_genes)],
    )
    ann_df = pd.DataFrame(
        {
            "batch": [f"B{i % 3}" for i in range(n_samples)],
            "bio": [f"T{i % 2}" for i in range(n_samples)],
            "cohort": [f"C{i % 4}" for i in range(n_samples)],
        },
        index=samples,
    )
    return exp_df, ann_df


def probe_metric_keys() -> dict[str, list[str]]:
    """
    Run every probeable group and report the metric keys it returns.

    Returns
    -------
    Letter to sorted key list. Groups in :data:`UNPROBED_GROUPS` are absent.
    """
    from combobatch.config import ColumnSpec, MetricsSpec
    from combobatch.metrics import GROUP_LETTERS
    from combobatch.metrics.runner import compute_metrics

    exp_df, ann_df = _fixture()
    columns = ColumnSpec(batch="batch", bio="bio", cohort="cohort")
    # Small permutation counts: the key *names* do not depend on them, and this keeps
    # documentation generation to a few seconds.
    spec = MetricsSpec(
        skip_slow=False,
        skip_wm=False,
        n_perm=2,
        wm_permutations=5,
        dsc_permutations=9,
        min_test_n=5,
        min_cohort_n=2,
        n_pcs=3,
    )

    probed: dict[str, list[str]] = {}
    for letter in GROUP_LETTERS:
        if letter in UNPROBED_GROUPS:
            continue
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            result = compute_metrics(
                exp_df,
                ann_df,
                columns,
                groups=frozenset(letter),
                ref_df=exp_df,
                spec=spec,
            )
        probed[letter] = sorted(
            key
            for key in result
            if key != "metrics_groups_run" and not key.startswith("error_")
        )
    return probed


def _param_row(param: Any) -> str:
    """Render one hyperparameter as a markdown table row."""
    type_name = getattr(param.type, "__name__", str(param.type))
    bounds = []
    if param.choices:
        bounds.append("one of " + ", ".join(f"`{c}`" for c in param.choices))
    if param.minimum is not None:
        bounds.append(f"min {param.minimum}")
    if param.maximum is not None:
        bounds.append(f"max {param.maximum}")
    r_arg = f"`{param.r_argument}`" if param.r_argument else "—"
    return (
        f"| `{param.name}` | {type_name} | `{param.default!r}` | "
        f"{', '.join(bounds) or '—'} | {param.help or ''} | {r_arg} |"
    )


def render_methods() -> str:
    """Render `docs/METHODS.md` from ``METHOD_REGISTRY`` and ``EXCLUDED_METHODS``."""
    from combobatch.methods import EXCLUDED_METHODS, METHOD_REGISTRY

    lines = [
        BANNER,
        "",
        "# Methods",
        "",
        f"**{len(METHOD_REGISTRY)} harmonization methods** are registered. Five more are "
        "deliberately absent; see the bottom of this page for each one's reason.",
        "",
        "`combobatch list-methods` prints this same table from the same registry, and "
        "`--available-only` narrows it to what your environment can actually run.",
        "",
        "## The registry",
        "",
        "| Key | Harshness | Backend | RNA-seq only | Uses reference batch | Tunable |",
        "|---|---|---|---|---|---|",
    ]

    for key, spec in METHOD_REGISTRY.items():
        backends = []
        if spec.requires_r:
            backends.append(
                "R: " + ", ".join(spec.r_packages) if spec.r_packages else "R"
            )
        if spec.requires_octave:
            backends.append("Octave")
        backends.extend(f"py: {name}" for name in spec.python_packages)
        params = ", ".join(f"`{name}`" for name in spec.hyperparams) or "—"
        lines.append(
            f"| `{key}` | {spec.harshness} | {'; '.join(backends) or 'pure Python'} | "
            f"{'yes' if spec.rnaseq_only else 'no'} | "
            f"{'yes' if spec.uses_reference_batch else 'no'} | {params} |"
        )

    lines += [
        "",
        "## Citations and notes",
        "",
    ]
    for key, spec in METHOD_REGISTRY.items():
        lines.append(f"**`{key}`** — {spec.citation or 'no citation recorded.'}")
        if spec.notes:
            lines.append(f"  {spec.notes}")
        lines.append("")

    lines += [
        "## Three rules that apply across methods",
        "",
        "**The RNA-seq-only guard.** Methods marked *RNA-seq only* model counts and are "
        "meaningless on microarray intensities. Rather than producing plausible nonsense, "
        "they raise `NotImplementedError` when the batch column contains a non-RNA-seq "
        "batch — an honest skip, recorded as such in the sidecar.",
        "",
        "**Reference-batch resolution.** Methods marked *uses reference batch* map every "
        "batch onto one target. When `target_group` is not given it resolves to **the "
        "largest batch in the data**, never to a hardcoded name. Set `--reference-batch` "
        "to choose a different target space.",
        "",
        "**Harshness** is how aggressively a method reshapes the matrix: `low` methods "
        "adjust location and scale, `high` methods reshape the distribution itself. It "
        "travels into every sidecar so a result can be read alongside how much violence "
        "was done to get it.",
        "",
        "## `20_shambhala` is a re-implementation",
        "",
        "The original Shambhala is an R package that was not usable here. `20_shambhala` "
        "is the vendored pure-Python plus Octave implementation, which follows the same "
        "algorithm but is not bit-identical to the R original. Numbers from it should not "
        "be compared directly against published Shambhala results without saying so.",
        "",
        "Two constraints it does not share with any other method: input must be **raw, "
        "not log-scale** (it applies its own `log2(x+1)` and has no scale detection), and "
        "its parallelism **multiplies** with the dispatcher's — total Octave processes are "
        "outer workers times its own `n_workers`.",
        "",
        f"## Deliberately absent ({len(EXCLUDED_METHODS)})",
        "",
        "These keys existed upstream and are not registered here. The numbering keeps its "
        "gaps so that a key always means the same method it always meant.",
        "",
        "| Key | Why |",
        "|---|---|",
    ]
    for key, reason in EXCLUDED_METHODS.items():
        lines.append(f"| `{key}` | {reason} |")

    lines += [
        "",
        "`39_procrustes` deserves the longest note. It is not a technical exclusion: the "
        "implementation works. It is BostonGene proprietary, licensed for non-commercial "
        "research only, and its licence forbids altering copyright notices — all three of "
        "which are incompatible with an MIT-licensed public tool. No clone, no `sys.path` "
        "insertion, no optional dependency: it is absent from the image entirely.",
        "",
    ]
    return "\n".join(lines) + "\n"


def render_hyperparameters() -> str:
    """Render `docs/HYPERPARAMETERS.md` from both the method and imputer registries."""
    from combobatch.imputation import IMPUTER_REGISTRY
    from combobatch.methods import METHOD_REGISTRY

    tunable = {k: s for k, s in METHOD_REGISTRY.items() if s.hyperparams}
    lines = [
        BANNER,
        "",
        "# Hyperparameters",
        "",
        "Every tunable parameter of every imputer and method, with its type, default and "
        "bounds. This is the feature the tool exists for: in the pipeline it was ported "
        "from, all of these were unreachable, so a benchmark could never answer *would a "
        "different setting have done better?*",
        "",
        f"{len(tunable)} of {len(METHOD_REGISTRY)} methods take parameters; the rest have "
        "nothing to tune.",
        "",
        "## How to pass them",
        "",
        "```bash",
        "# one method, one parameter",
        "combobatch run --exp e.tsv.gz --ann a.csv --out out/ \\",
        "    --batch-col BATCH --bio-col CLASS \\",
        "    --imputation knn --method 10_mnn --method-params '10_mnn:k=50'",
        "",
        "# several, and on the imputer too",
        "combobatch dispatch --config base.yaml \\",
        "    --method-params '10_mnn:k=50,11_harmony:n_pcs=30' \\",
        "    --imputation-params 'knn:knn_k=15'",
        "```",
        "",
        "```yaml",
        "methods:",
        "  - name: 10_mnn            # defaults",
        "  - name: 10_mnn            # and a second run at k = 50",
        "    params: {k: 50}",
        "```",
        "",
        "A parameter name that no method declares is rejected **before** anything is "
        "downloaded, with a did-you-mean suggestion. So is a value of the wrong type.",
        "",
        "## What tuning does to the output name",
        "",
        "A selection that is not at pure defaults gets a parameter tag, so two runs of one "
        "method cannot overwrite each other:",
        "",
        "```",
        "strict__10_mnn.tsv.gz          # defaults - no tag",
        "strict__10_mnn__k50.tsv.gz     # k = 50",
        "```",
        "",
        "`run_manifest.json` maps every tag back to the parameters it stands for. The "
        "imputer and the method share one tag slot, so tuning the same parameter name on "
        "both sides is rejected rather than silently resolved. Override a generated tag "
        "with `param_tag` when it would otherwise be unwieldy.",
        "",
        "## Imputers",
        "",
    ]

    for key, spec in IMPUTER_REGISTRY.items():
        lines += [
            f"### `{key}`",
            "",
            spec.description or "",
            "",
            "| Parameter | Type | Default | Bounds | Meaning | R argument |",
            "|---|---|---|---|---|---|",
        ]
        lines += [_param_row(param) for param in spec.hyperparams.values()]
        lines.append("")

    lines += ["## Methods", ""]
    for key, spec in tunable.items():
        lines += [
            f"### `{key}`",
            "",
            spec.citation or "",
            "",
            "| Parameter | Type | Default | Bounds | Meaning | R argument |",
            "|---|---|---|---|---|---|",
        ]
        lines += [_param_row(param) for param in spec.hyperparams.values()]
        lines.append("")

    untunable = [k for k in METHOD_REGISTRY if k not in tunable]
    lines += [
        "## Methods with nothing to tune",
        "",
        ", ".join(f"`{key}`" for key in untunable),
        "",
        "## Which parameters actually matter",
        "",
        "From the source benchmark's variance decomposition, the choice of **method** "
        "dominates (36.3% of outcome variance), then the **subset** of data (25.6%), then "
        "**imputation** (1.6%), then post-removal (0.2%). Tuning within a method moves "
        "results far less than choosing a different method — so sweep across methods "
        "first, and tune second.",
        "",
        "Two exceptions worth the time: `10_mnn`'s `k`, which controls how aggressively "
        "batches are merged and interacts strongly with batch size, and `target_group` on "
        "the reference-based methods, which decides *which* platform everything else is "
        "mapped onto.",
        "",
    ]
    return "\n".join(lines) + "\n"


def render_metrics() -> str:
    """Render `docs/METRICS.md` from ``METRIC_GROUP_REGISTRY``, probing emitted keys."""
    from combobatch.metrics import (
        DEFAULT_GROUPS,
        GROUP_LETTERS,
        METRIC_GROUP_REGISTRY,
    )

    probed = probe_metric_keys()
    lines = [
        BANNER,
        "",
        "# Metrics",
        "",
        f"**{len(METRIC_GROUP_REGISTRY)} groups, A-N.** Each is independent: a group that "
        "fails records `error_<LETTER>` and the others still run, and a group whose "
        "sentinel key is already present is not recomputed, so groups can be added to a "
        "finished run without redoing the rest.",
        "",
        f"By default `{','.join(sorted(DEFAULT_GROUPS))}` run — the fast ones that need no "
        "R and no permutations.",
        "",
        "```bash",
        "combobatch metrics --config c.yaml --groups A,B,E,J,K",
        "combobatch metrics --config c.yaml --groups all --force-groups F",
        "```",
        "",
        "## Reading a metric name",
        "",
        "Metric keys carry **the column they were computed against**, taken from your "
        "`ColumnSpec` — the same group emits `r2_site` on one dataset and "
        "`r2_sequencing_run` on another. Nothing here has an opinion about what your "
        "columns are called.",
        "",
        "That also means polarity depends on the column: a batch-keyed metric and a "
        "biology-keyed metric from the same group usually point in opposite directions. "
        "The polarity column below says which is which.",
        "",
        "## The groups",
        "",
        "| Group | Name | Cost | Default | Needs | Polarity |",
        "|---|---|---|---|---|---|",
    ]

    for letter in GROUP_LETTERS:
        spec = METRIC_GROUP_REGISTRY[letter]
        needs = []
        if spec.needs_r:
            needs.append("R")
        if spec.needs_reference:
            needs.append("reference matrix")
        if spec.needs_panel:
            needs.append("marker panel")
        needs.extend(spec.needs_embedding)
        lines.append(
            f"| **{letter}** | {spec.name} | {spec.speed} | "
            f"{'yes' if letter in DEFAULT_GROUPS else 'no'} | "
            f"{', '.join(needs) or '—'} | {spec.polarity} |"
        )

    lines.append("")
    for letter in GROUP_LETTERS:
        spec = METRIC_GROUP_REGISTRY[letter]
        lines += [
            f"### {letter} — {spec.name}",
            "",
            spec.description,
            "",
            f"- **Sentinel key:** `{spec.sentinel_template}`",
            f"- **Columns consumed:** {', '.join(spec.column_roles) or 'none'}",
            f"- **Polarity:** {spec.polarity}",
            f"- **Cost:** {spec.speed}",
            f"- **Citation:** {spec.citation}",
        ]
        if letter in probed:
            keys = ", ".join(f"`{key}`" for key in probed[letter])
            lines.append(f"- **Keys emitted** ({len(probed[letter])}): {keys}")
        else:
            lines.append(
                "- **Keys emitted:** not enumerated here — this group needs R, and "
                "probing it would make this file differ between environments."
            )
        lines.append("")

    lines += [
        "## Two caveats that change how these are read",
        "",
        "**Group L saturates.** Its within-cohort correlation reaches exactly 1.0 for any "
        "per-gene monotone transform, which most linear harmonization methods are. It is "
        "a guard rail that catches a method destroying the biology, not a ranking that "
        "distinguishes good methods from better ones. Group M's margin carries the "
        "discriminative signal instead.",
        "",
        "**Global and local metrics disagree, and both are needed.** In the source "
        "benchmark the two families were near-orthogonal (median Spearman r ≈ 0.009): a "
        "good PCA R² coexists comfortably with batches that remain separated locally. "
        "Reading only one family is how a method gets called good when it is not.",
        "",
        "## Cost",
        "",
        "`--skip-slow` drops every group marked `very_slow` and names each exclusion in "
        "the log with the flag that undoes it. `--force-groups` beats every exclusion, "
        "including an existing sentinel.",
        "",
    ]
    return "\n".join(lines) + "\n"


# Filename to renderer. `scripts/generate_docs.py` and the sync test both read this, so
# adding a generated doc means adding one entry and nothing else.
GENERATED_DOCS: dict[str, Callable[[], str]] = {
    "METHODS.md": render_methods,
    "HYPERPARAMETERS.md": render_hyperparameters,
    "METRICS.md": render_metrics,
}
